module Euler.Problem2 where

-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
--
-- Answer: 4613732

fibs :: [Int]
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)

problem2 :: Int
problem2 = 
	sum
	$ filter even
	$ drop 2
	$ takeWhile (\x -> x < 4000000)
	$ fibs

main :: IO()
main = print problem2 